### ISSUE TITLE
Support optional values

### ISSUE THREAD

**Issue by jlorenzen** [orangain/json-fuzzy-match#33]
Love the idea of being able to do json fuzzy matching that's near identical with Karate. Be great if this project supported optional properties like Karate does. See: https://github.com/karatelabs/karate?tab=readme-ov-file#optional-fields

**Comment by orangain** [comment]
Sounds good! I think I can get time to implement it over the weekend. Of course, pull request is welcome.

**Comment by orangain** [comment]
@jlorenzen I have released the version [0.7.0](https://github.com/orangain/json-fuzzy-match/releases/tag/0.7.0) that supports [optional values](https://github.com/orangain/json-fuzzy-match?tab=readme-ov-file#optional-marker). Thank you for your suggestion.

**Comment by jlorenzen** [comment]
Thanks for doing this @orangain! Really appreciate it.
